### ISSUE TITLE
Can we transfer data only to a specific listener?

### ISSUE THREAD

**Issue by Samykills** [chirp/chirp-react-native#20]
Is it possible to transfer to a specific device when i have a bunch of devices on listening mode?

**Comment by joextodd** [comment]
You can with a multichannel protocol. See the documentation at https://developers.chirp.io/docs/using-chirp/multichannel

**Comment by Samykills** [comment]
if i have multiple devices listening on the same channel is there any way using the sdk that i can distinguish between the devices? and send data to only one of the targeted device??
