### ISSUE TITLE
Send ultrassonic data

### ISSUE THREAD

**Issue by fssantos** [chirp/chirp-react-native#23]
Hello guys,

What such nice wrapper!

Everytime I send data it's not inaudible. I was expecting that once my key and secret are configured as ultrasound on chirp dashboard then my device would emit a ultrasound as well when sending.

Am I missing something?

I tried to use setConfig() as well insted of setConfigFromNetwork() but there's always a noise in place of ultrasound.

For receiving everything works.

**Comment by joextodd** [comment]
@fssantos if you are receiving ok then everything is correct with the config. Could you specify 

- Which device you are using? 
- Which ChirpSDK version is running?
- And if possible attach a recording of the audio to this thread?

**Comment by fssantos** [comment]
@joextodd that was my fault. Actually I was expecting that the sound I send would be received on the same device, which is not true and really nice \o/.

Due to this thought I've put my device volume on maximum while testing it and for this reason I was able to hear a small noise (like a dial up connection and not loud). Take look on the .wav bellow.

https://drive.google.com/file/d/1Md36ElEgUYzepohbsXvOZVb4vIVm7QMZ/view

BUT, it only happens on maximum volume (Motorola Moto G6, Chirp SDK 3.7). On my gf smartphone you hear nothing as expected even in high volumes. And everything works fine between both devices (send and receive - ultrasound). 

The noise itself is not an issue for me once it's not a real noise but something like dial up connection sound and only happens on max volume.

**Comment by joextodd** [comment]
@fssantos that is the default behaviour, you can make the SDK listen to itself for testing, see [here](https://docs.chirp.io/android/chirpsdk/io.chirp.connect/-chirp-connect/set-listen-to-self.html)

Can you try bumping the Android version to v3.8.0? We introduced a fix for this bug in that release.

Please reopen the issue if this doesn't solve the problem.
